name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rodar app
        run: python app.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "Novo commit feito no repositório!"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
